name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    env:
      var.subscription_id = "0411661d-786d-4479-8461-8112a276c510"
      var.client_id       = "38391a70-70d0-42ff-a4d6-a6d89d9a9fdc"
      var.client_secret   = "pTx8Q~MEzOk5M32p6ihIgVSfK2vgFg7N8QmQybYy"
      var.tenant_id       = "c01407f9-0318-447d-b0a3-afc95a957f86"


    steps:
  # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4.1.1

  # Install the preferred version of Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7


      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
          
      - name: Terraform Apply
        run: terraform apply -auto-approve

